#Appendix A: Bonus Lesson on Applying SQL with Python
#Exercises
#Written on: January 14, 2024

In [2]:
# Exercise A.1: Creating an Employee Database
# Create a database employeedb
# What happens if you run this command more than once?

import pymysql

#update connection data as required for the local MySQL setup
con = pymysql.connect(host='localhost', user='root', password='password123')
with con:
    cur = con.cursor()
    cur.execute('CREATE DATABASE employeedb;')

print('Database created')

# Running this command more than once will result in Programming Error because database already exist
# ProgrammingError: (1007, "Can't create database 'employeedb'; database exists")

ProgrammingError: (1007, "Can't create database 'employeedb'; database exists")

In [1]:
# Exercise A.2: Removing a Database
# Delete the employeedb database
# What happens if you delete a database you have already deleted?

import pymysql

#update connection data as required for the local MySQL setup
con = pymysql.connect(host='localhost', user='root', password='admin', db='employeedb')
with con:
    cur = con.cursor()
    cur.execute("DROP DATABASE employeedb;")
    
print("Database deleted")

# Deleting a database more than once will give OperationalError: (1049, "Unknown database 'employeedb'").

OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

In [50]:
# Exercise A.3: Creating a Table of Employees
# Write a script that will drop and rebuild an employee table in a database called employeedb.
# The table should be created with all attributes shown here:

# employee_id int(10) NOT NULL AUTO_INCREMENT,
# empLastName varchar(50) NOT NULL,
# empFirstName varchar(35) NOT NULL,
# empMidInit char(1),
# PRIMARY KEY (employee_id)

import pymysql

#update connection data as required for the local MySQL setup
con = pymysql.connect(host='localhost', user='root', password='admin')
with con:
    cur = con.cursor() #create a curson object
    cur.execute("DROP DATABASE IF EXISTS employeedb;")
    cur.execute("CREATE DATABASE employeedb;")
    cur.close() #close connection to MySQL
print("Database created")


# Now, let's create an employee table

create_table_query = """
                CREATE TABLE employees (
                    employee_id int(10) NOT NULL AUTO_INCREMENT,
                    empLastName varchar(50) NOT NULL,
                    empFirstName varchar(35) NOT NULL,
                    empMidInit char(1) NULL,
                    PRIMARY KEY (employee_id));
                    """
print(create_table_query)

show_table_query = """SHOW TABLES;"""

describe_table_query = """DESCRIBE employees;"""

#update connection data as required for the local MySQL setup
con = pymysql.connect(host='localhost', user='root', password='admin', db='employeedb')
with con:
    cur = con.cursor() #create a cursor object used to execute MySQL queries.
    cur.execute(create_table_query)
    
    cur.execute(show_table_query)
    for row in cur:
        print(row[0])
        
        cur.execute(describe_table_query)
        for row in cur:
            print(row)

Database created

                CREATE TABLE employees (
                    employee_id int(10) NOT NULL AUTO_INCREMENT,
                    empLastName varchar(50) NOT NULL,
                    empFirstName varchar(35) NOT NULL,
                    empMidInit char(1) NULL,
                    PRIMARY KEY (employee_id));

employees
('employee_id', 'int', 'NO', 'PRI', None, 'auto_increment')
('empLastName', 'varchar(50)', 'NO', '', None, '')
('empFirstName', 'varchar(35)', 'NO', '', None, '')
('empMidInit', 'char(1)', 'YES', '', None, '')

In [51]:
# Exercise A.3: Adding Employees
# Create a script that adds at least 10 valid records to the employee table employeedb
# What happens if you run the same script more than once?
# Do you have to include values for the employee_id field? What happens if you don't?
# You may need to drop and rebuild the table multiple times to answer these questions.

import pymysql

insert_table_query = """INSERT INTO employees(employee_id, empLastName, empFirstName, empMidInit)
                    VALUES
                        (1,'Ulzi', 'Fousey', 'Y'),
                        (2, 'Garcia', 'Robert', 'M'),
                        (3, 'Lai', 'Dang', 'W'),
                        (4, 'Lennon', 'Jon',null),
                        (5, 'Pascal', 'Will', 'A'),
                        (6, 'Swift', 'Taylor', 'T'),
                        (7, 'Johnson', 'Johnson',null),
                        (8, 'Aaron', 'Baron', 'L'),
                        (9, 'Doe', 'John', 'U'),
                        (10, 'Smith', 'William', 'H');
                        """

view_records = """SELECT * 
                    FROM employees;"""

#update connection data as required for the local MySQL setup
con = pymysql.connect(host='localhost', user='root', password='admin', db='employeedb')
with con:
    cur = con.cursor() #create a cursor object used to execute MySQL queries.
    cur.execute(insert_table_query)
    
    cur.execute(view_records)
    con.commit()
    for row in cur:
        print(row)
 # Yes, you do have to include values in employee_id

(1, 'Ulzi', 'Fousey', 'Y')
(2, 'Garcia', 'Robert', 'M')
(3, 'Lai', 'Dang', 'W')
(4, 'Lennon', 'Jon', None)
(5, 'Pascal', 'Will', 'A')
(6, 'Swift', 'Taylor', 'T')
(7, 'Johnson', 'Johnson', None)
(8, 'Aaron', 'Baron', 'L')
(9, 'Doe', 'John', 'U')
(10, 'Smith', 'William', 'H')

In [32]:
# Exercise A.5: Retrieving Employees
# Write scripts that perform the following tasks on the data in the employeedb.employee table:
# Retrieve all records from all fields and display results.
# Retrieve and display only the first and last name values, sorted by last name and then by first name.
# Retrieve and display all name fields only for records where a middle initial is present in the data.
# Can you think of any other questions you could ask about the data?

import pymysql

all_fields_query = """SELECT *
                    FROM employees;"""

first_last_query = """SELECT empFirstName, empLastName
                        FROM employees;"""

mid_not_null = """SELECT empFirstName, empLastName, empMidInit
                    FROM employees
                    WHERE empMidInit IS NOT NULL;"""

#update connection data as required for the local MySQL setup
con = pymysql.connect(host='localhost', user='root', password='admin', db='employeedb')
with con:
    cur = con.cursor()
    cur.execute(all_fields_query)
    for row in cur:
        print(row)
        
    cur.execute(first_last_query)
    for row in cur:
        print(row)
        
    cur.execute(mid_not_null)
    for row in cur:
        print(row)

(1, 'Ulzi', 'Fousey', 'Y')
(2, 'Garcia', 'Robert', 'M')
(3, 'Lai', 'Dang', 'W')
(4, 'Lennon', 'Jon', None)
(5, 'Pascal', 'Will', 'A')
(6, 'Swift', 'Taylor', 'T')
(7, 'Johnson', 'Johnson', None)
(8, 'Aaron', 'Baron', 'L')
(9, 'Doe', 'John', 'U')
(10, 'Smith', 'William', 'H')
('Fousey', 'Ulzi')
('Robert', 'Garcia')
('Dang', 'Lai')
('Jon', 'Lennon')
('Will', 'Pascal')
('Taylor', 'Swift')
('Johnson', 'Johnson')
('Baron', 'Aaron')
('John', 'Doe')
('William', 'Smith')
('Fousey', 'Ulzi', 'Y')
('Robert', 'Garcia', 'M')
('Dang', 'Lai', 'W')
('Will', 'Pascal', 'A')
('Taylor', 'Swift', 'T')
('Baron', 'Aaron', 'L')
('John', 'Doe', 'U')
('William', 'Smith', 'H')

In [48]:
# Exercise A.6: Updating Employees
# Change employee's last name.
# Change the first and last names of one employee using the same UPDATE statement.
# Attempt to run an UPDATE statement without the WHERE clause to see what happens.
# Can you change any of the employeeid values?
# You might need to drop and rebuild the database a few times.

import pymysql

select_query = """SELECT *
                FROM employees
                WHERE employee_id = 3;"""

update_query = """UPDATE employees
            SET empLastName = 'Lai';"""

#use appropriate values to connect to the local MySQL sever
con = pymysql.connect(host='localhost', user='root', password='admin', db='employeedb')
with con:
    cur = con.cursor()          # create a cursor object.
    cur.execute(select_query) # view the record before changing the date
    for row in cur:
        print(row)
    
    cur.execute(update_query) # execute the update query
    
    con.commit()
    
    cur.execute(select_query)  # view the record after changing the data
    for row in cur:
        print(row)
        
# Without the WHERE clause, the UPDATE statement is executed to all the other employees.
# Can't change Primary Keys

(3, 'Chan', 'Dang', 'W')
(3, 'Lai', 'Dang', 'W')

In [62]:
# Exercise A.7: Deleting Employees
# Use DELETE statement to delete a record in the employee table.
# What happens if you attempt to delete a record that does not exist?
# Can you delete multiple records at the same time with the same criteria?
# What does the query DELETE FROM tablename do?
# You might need to drop and rebuild the database multiple times.

import pymysql
select_query = """SELECT *
                FROM employees;"""

update_query = """DELETE FROM employees;"""

#use appropriate values to connect to the local MySQL sever
con = pymysql.connect(host='localhost', user='root', password='admin', db='employeedb')
with con:
    cur = con.cursor()          # create a cursor object.
    cur.execute(select_query) # view record table before changing the data
    for row in cur:
        print(row)
    
    cur.execute(update_query) # execute update query
    
    con.commit()
    
    cur.execute(select_query) # view the record after changing the data
    for row in cur:
        print(row)
        
# Deleting a record that does not exist will result in no action.
# Yes, you can delete multiple records at the same time.
# The query DELETE FROM tablename deletes all the record in the table.

(1, 'Ulzi', 'Fousey', 'Y')
(2, 'Garcia', 'Robert', 'M')
(4, 'Lennon', 'Jon', None)
(7, 'Johnson', 'Johnson', None)
(8, 'Aaron', 'Baron', 'L')
(9, 'Doe', 'John', 'U')

In [2]:
# Exercise A.8: Nobel Laureates
# Use Nobel Laureates dateset called laureate.json
# Transform the JSON data into a suitable format to save the data in MySQL.
# Implement the necessary code to save the data to MySQL.
# Identify the Laureate with the most Nobel Prizes.
# What country has the most Laureates?
# What city has the most Laureates?

In [ ]:
# Exercise A.9: Restaurants
# Use dataset restaurants.json
# Write the Python code that will import the restaurant data to MySQL.
# Create the necessary tables in MySQL to store the data in the most efficient way.
# Create the necessary code in Python to read the data from the JSON file and import it into the MySQL tables
# After moving the data to MySQL, use Python and MySQL to find the following information:
# Compute the average score for each restaurant.
# Compute the minimum score for each restaurant.
# Compute the maximum score for each restaurant.
# Compute the average score for each type of cuisine in each borough.
# Compute the minimum score for each type of cuisine in each borough.
# Compute the maximum score for each type of cuisine in each borough.